say "Installing default Rubocop configuration for projects at UB Paderborn"

create_file ".rubocop_todo.yml"
create_file ".rubocop_custom.yml"
create_file ".rubocop.yml", <<~YML
  #
  # Automatically generated by `rails ubpb:rubocop-config:install`
  #
  # Based on: https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard
  #
  # !!DO NOT EDIT MANUALLY!!
  # Use .rubocop_custom.yml instead
  #
  inherit_gem:
    ubpb-rubocop-config: config/base.yml

YML
