Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: true

Lint/Debugger: # don't leave binding.pry or debugger
  Enabled: true
  Exclude: []
