  inherit_mode:
    merge:
      - Exclude

  require:
    - standard
    - rubocop-performance
    - rubocop-rails

  inherit_gem:
    standard: config/base.yml
    standard-performance: config/base.yml
    standard-custom: config/base.yml

  inherit_from: # order matters
    #- "https://raw.githubusercontent.com/ubpb/rubocop-config/main/config/rails.yml"
    #- "https://raw.githubusercontent.com/ubpb/rubocop-config/main/config/custom.yml"
    - .rubocop_todo.yml
    #- "https://raw.githubusercontent.com/ubpb/rubocop-config/main/config/strict.yml"
    - .rubpcop_custom.yml

  AllCops:
    SuggestExtensions: false
    TargetRubyVersion: 3.2
